### ISSUE TITLE
Hanging at "echo mem > /sys/power/state"

### ISSUE THREAD

**Issue by seanlynch** [vianney/arch-luks-suspend#2]
For some reason the system just hangs at the point where it tries to suspend to RAM. If I comment out the luksSuspend and luksResume lines it works fine. At first I thought it was journald but I both deleted /var/log/journal so it wouldn't keep a persistent log and then tried shutting down journald entirely before suspending. I'm guessing something else is trying to access the disk during the final suspend. Any thoughts?

**Comment by vianney** [comment]
Fixed in 15420df7134aad95b515b747af0b99f216aeb9ed
